### ISSUE TITLE
如何在idea中对docker容器中的FE代码进行DEBUG

### ISSUE THREAD

**Issue by zhangxuan183** [Smith-Cruise/StarRocks-Docker-Dev#1]

**Comment by Smith-Cruise** [comment]
你贴一下 IDEA 的 Remote Debug 设置吧。

**Comment by Smith-Cruise** [comment]
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/18729228/186417737-b83e6de0-976b-48fd-badc-f7b42b838e6d.png">

这个是我的。

**Comment by zhangxuan183** [comment]
![2e902ff7-c563-4b87-b922-e6cbd4030c06](https://user-images.githubusercontent.com/61973476/186418580-50c44a70-ac7c-4fe6-a49a-5629455c25e6.jpg)

**Comment by zhangxuan183** [comment]
这个是我的

**Comment by Smith-Cruise** [comment]
给我看看你 start_fe.sh 那行怎么改的。

**Comment by zhangxuan183** [comment]
if [ ${RUN_DAEMON} -eq 1 ]; then
    nohup $LIMIT $JAVA $final_java_opt com.starrocks.StarRocksFE ${HELPER} "$@" >> $LOG_DIR/fe.out 2>&1 </dev/null &
else
    $LIMIT $JAVA $final_java_opt -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001 com.starrocks.StarRocksFE ${HELPER} "$@" >> $LOG_DIR/fe.out 
fi

**Comment by zhangxuan183** [comment]
不是，我截个图

**Comment by zhangxuan183** [comment]
![image](https://user-images.githubusercontent.com/61973476/186420510-e370b897-808a-4a78-b035-c09284e1522a.png)

**Comment by zhangxuan183** [comment]
提示消息是可以链接上的，但是会瞬间结束，而且如果是在main函数debug的话，应该三个服务端口起不起来才对吧

**Comment by zhangxuan183** [comment]
每次三个端口都是会直接启动起来

**Comment by zhangxuan183** [comment]
我是在starrocks的output文件下改动的，是不是应该在fe项目里面改，才有效果？

**Comment by Smith-Cruise** [comment]
你 start_fe.sh 启动后，有显示出：
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/18729228/186421980-75131a36-eb66-4f33-941d-942bf88a7868.png">
这样吗

**Comment by zhangxuan183** [comment]
有的，你start_fe.sh 之后，fe的几个端口转发都打开了吗

**Comment by zhangxuan183** [comment]
可不可以映射一个端口，通过idea的docker插件创建连接，以此访问，直接运行的方式，就像remote虚拟机一样

**Comment by Smith-Cruise** [comment]
当然要转发端口，不然你怎么访问的到docker里面的port。
方法很多，能到达目的就行了。
