### ISSUE TITLE
Clion远程连接Docker环境，BE代码没有高亮，方法间不能正常跳转

### ISSUE THREAD

**Issue by tomscut** [Smith-Cruise/StarRocks-Docker-Dev#2]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/55134131/191638800-0bf10b58-7d76-4d63-a7e8-721de25648c1.png">

**Comment by Smith-Cruise** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/18729228/191640336-7a06c61d-098f-444d-bb71-0ee81554ee69.png">

**Comment by Smith-Cruise** [comment]
这里配置过 remote host 吗

**Comment by tomscut** [comment]
配置过了，代码同步没有问题。不过我刚刚尝试删除.idea目录，再重启Clion，.cpp文件看起来可以了，但是头文件还不行。
<img width="408" alt="image" src="https://user-images.githubusercontent.com/55134131/191640877-dc058909-4fc5-40a3-ace8-8e5ccda327a6.png">

**Comment by Smith-Cruise** [comment]
你docker里面也同步了代码吧

**Comment by Smith-Cruise** [comment]
你在docker里面先尝试编译一次看看
sh build.sh

**Comment by tomscut** [comment]
请问这里的Mappings和Excluded Paths，你是怎么配置的呢？
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/55134131/191641605-bcb6e2ec-902a-4dbf-8f27-9811e5456731.png">

**Comment by Smith-Cruise** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/18729228/191642273-3d95c0b1-86dc-4683-918f-f57afe228aef.png">

**Comment by Smith-Cruise** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/18729228/191642318-2696ac70-c98a-431f-8efc-24dc0bc8d01b.png">

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/18729228/191642340-ff39fef7-3ce0-476a-aee0-8dcf242ea2cd.png">

**Comment by tomscut** [comment]
谢谢！我看到文章里面启动docker的时候，加了目录映射，然后clion里面也配置了文件同步。那是不是会有冲突，相当于2个地方在做内容同步？

**Comment by Smith-Cruise** [comment]
额，对你来说可能是的。因为我开发机在远程，所以我需要同步，像你就不需要了。

**Comment by tomscut** [comment]
好的，多谢大佬！我发现头文件虽然没有高亮，但代码可以跳转的。不过在编译代码的时候，遇到这种问题：
![image](https://user-images.githubusercontent.com/55134131/191686272-dc529054-cf53-4cd3-a035-b126e3c20892.png)

**Comment by Smith-Cruise** [comment]
你是在docker里面编译吗，docker里面不可能不行呀，你直接 sh build.sh 就行了。

**Comment by tomscut** [comment]
我发现编译失败，是内存不足导致的，核心的报错是：`C++: fatal error: Killed signal terminated program cc1plus`.

请问你在容器当中执行systemctl命令会报：`Failed to get D-Bus connection: Operation not permitted` 吗？

**Comment by Smith-Cruise** [comment]
容器里面本来就不能执行 systemctl 的，你先把内存搞多点吧。
内存至少要 8GB。

**Comment by tomscut** [comment]
嗯，加内存是可以的。本来想加一下swap，发现加不了。

**Comment by tomscut** [comment]
那这个issue应该可以close了。多谢啦！

**Comment by huldarchen** [comment]
@tomscut 您好，可以留个联系方式 指导下开发环境搭建吗？谢谢。

**Comment by huldarchen** [comment]
@Smith-Cruise 
> <img alt="image" width="1018" src="https://user-images.githubusercontent.com/18729228/191640336-7a06c61d-098f-444d-bb71-0ee81554ee69.png">

可以看下cmake的参数吗？

**Comment by tomscut** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/55134131/202934764-be098ae9-d4ea-4629-8682-2757597a1e05.png">
Cmake的参数，我基本都是用默认的。我主要是参考博主的文章搭建的，不过我禁用了clion的文件同步功能，直接用docker同步，然后在docker容器内编译，启动fe和be。

**Comment by Smith-Cruise** [comment]
> @Smith-Cruise
> 
> > <img alt="image" width="1018" src="https://user-images.githubusercontent.com/18729228/191640336-7a06c61d-098f-444d-bb71-0ee81554ee69.png">
> 
> 可以看下cmake的参数吗？

其实现在开发环境改善很多，ubuntu 能直接编译了

**Comment by huldarchen** [comment]
我的be计划的开发方式是：本地code，利用clion同步到远程docker中，然后利用toolchains的remote host进行远程编译，目前编译成功了。
在本地clion中运行debug的starrocks_be提示libjvm.so没有找到。
![image](https://user-images.githubusercontent.com/41148123/202951885-d2e1ff00-c5cf-4d81-9b72-e4e1eaaa7ac3.png)
由于对C++不熟悉，可能我这种方式本身就是错误的。

在docker中通过./bin/start_be.sh运行是成功的

**Comment by Smith-Cruise** [comment]
> 我的be计划的开发方式是：本地code，利用clion同步到远程docker中，然后利用toolchains的remote host进行远程编译，目前编译成功了。 在本地clion中运行debug的starrocks_be提示libjvm.so没有找到。 ![image](https://user-images.githubusercontent.com/41148123/202951885-d2e1ff00-c5cf-4d81-9b72-e4e1eaaa7ac3.png) 由于对C++不熟悉，可能我这种方式本身就是错误的。
> 
> 在docker中通过./bin/start_be.sh运行是成功的

在 clion 中直接 debug 是不行的，要 ssh 进 docker debug。Clion 的 debug 不支持。

**Comment by huldarchen** [comment]
我建了个一个c++的Hello World测试了下，从运行命令来看是可以这样debug的。
Toochains配置
<img width="936" alt="image" src="https://user-images.githubusercontent.com/41148123/202955718-c00f6700-1390-4adb-b58b-cc94edeece6d.png">
CMake配置
<img width="938" alt="image" src="https://user-images.githubusercontent.com/41148123/202955566-f085182b-5aa8-4c85-b819-a177495a99a4.png">
Debug成功
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/41148123/202955518-1c3cd666-d3d6-4467-82df-ff99e34b8e04.png">

**Comment by huldarchen** [comment]
我建了一个c++的hello world项目测试了一下，这样debug从命令行来看是可以的。/tmp/tmp.tp52iFZmCu/cmake-build-debug/hello

Toolchains的配置信息
<img width="936" alt="image" src="https://user-images.githubusercontent.com/41148123/202958472-039e0a6e-39b9-432f-bfb6-abe56792eea6.png">

CMake的配置信息
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/41148123/202958669-07a9a267-18a1-4b19-9899-414d9a51544c.png">

deployment的配置信息
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/41148123/202959045-b1df0a03-c743-46a8-b965-75ed73e537db.png">
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/41148123/202959196-374d07a8-60a8-4e84-b929-4f1ed34a6986.png">

debug截图
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/41148123/202959352-99f75443-a79a-44fd-b0da-9750b087d832.png">

我推测会不会是在start_be.sh启动中增加了一些环境变量，而在clion的debug中缺少了一些环境变量导致异常。我再进一步实验下。

**Comment by huldarchen** [comment]
@Smith-Cruise @tomscut 测试了一下 增加环境变量后可以进行debug
首先通过clion进行远程编译，编译完成后 环境变量是通过 `sh -xv /root/starrocks/be/output/bin/start_be.sh`获取到，具体如下:
```
STARROCKS_HOME=/root/starrocks/be/output;
UDF_RUNTIME_DIR=/root/starrocks/be/output/lib/udf-runtime;
LOG_DIR=/root/starrocks/be/output/log;
PID_DIR=/root/starrocks/be/output/bin;
AWS_EC2_METADATA_DISABLED=true;
TCMALLOC_HEAP_LIMIT_MB=6717;
HADOOP_CLASSPATH=/root/starrocks/be/output/lib/hadoop/common/*:/root/starrocks/be/output/lib/hadoop/common/lib/*:/root/starrocks/be/output/lib/hadoop/hdfs/*:/root/starrocks/be/output/lib/hadoop/hdfs/lib/*;
HADOOP_USER_NAME=root;
LD_LIBRARY_PATH=/root/starrocks/be/output/lib/hadoop/native:/var/local/thirdparty/installed/open_jdk/jre/lib/amd64/server:/var/local/thirdparty/installed/open_jdk/jre/lib/amd64:/opt/rh/rh-mysql57/root/usr/lib64:/opt/rh/httpd24/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib:/opt/rh/devtoolset-11/root/usr/lib64/dyninst:/opt/rh/devtoolset-11/root/usr/lib/dyninst;
CLASSPATH=/root/starrocks/be/output/conf:/root/starrocks/be/output/lib/hadoop/common/*:/root/starrocks/be/output/lib/hadoop/common/lib/*:/root/starrocks/be/output/lib/hadoop/hdfs/*:/root/starrocks/be/output/lib/hadoop/hdfs/lib/*:;
JEMALLOC_CONF=percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000,metadata_thp:auto,background_thread:true;
ASAN_OPTIONS=abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1;
LSAN_OPTIONS=suppressions=/root/starrocks/be/output/conf/asan_suppressions.conf;
LIBHDFS_OPTS= -Xrs
```
将上述环境变量增加到clion的环境变量中如下图：
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/41148123/203332383-776d609c-ca68-4a30-a22d-3637fa6d894d.png">
然后就可以进行debug了
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/41148123/203332487-ee7ed10b-c8b2-430a-8a25-ff27cf7836ab.png">

**Comment by Smith-Cruise** [comment]
> @Smith-Cruise @tomscut 测试了一下 增加环境变量后可以进行debug 首先通过clion进行远程编译，编译完成后 环境变量是通过 `sh -xv /root/starrocks/be/output/bin/start_be.sh`获取到，具体如下:
> 
> ```
> STARROCKS_HOME=/root/starrocks/be/output;
> UDF_RUNTIME_DIR=/root/starrocks/be/output/lib/udf-runtime;
> LOG_DIR=/root/starrocks/be/output/log;
> PID_DIR=/root/starrocks/be/output/bin;
> AWS_EC2_METADATA_DISABLED=true;
> TCMALLOC_HEAP_LIMIT_MB=6717;
> HADOOP_CLASSPATH=/root/starrocks/be/output/lib/hadoop/common/*:/root/starrocks/be/output/lib/hadoop/common/lib/*:/root/starrocks/be/output/lib/hadoop/hdfs/*:/root/starrocks/be/output/lib/hadoop/hdfs/lib/*;
> HADOOP_USER_NAME=root;
> LD_LIBRARY_PATH=/root/starrocks/be/output/lib/hadoop/native:/var/local/thirdparty/installed/open_jdk/jre/lib/amd64/server:/var/local/thirdparty/installed/open_jdk/jre/lib/amd64:/opt/rh/rh-mysql57/root/usr/lib64:/opt/rh/httpd24/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib:/opt/rh/devtoolset-11/root/usr/lib64/dyninst:/opt/rh/devtoolset-11/root/usr/lib/dyninst;
> CLASSPATH=/root/starrocks/be/output/conf:/root/starrocks/be/output/lib/hadoop/common/*:/root/starrocks/be/output/lib/hadoop/common/lib/*:/root/starrocks/be/output/lib/hadoop/hdfs/*:/root/starrocks/be/output/lib/hadoop/hdfs/lib/*:;
> JEMALLOC_CONF=percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000,metadata_thp:auto,background_thread:true;
> ASAN_OPTIONS=abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1;
> LSAN_OPTIONS=suppressions=/root/starrocks/be/output/conf/asan_suppressions.conf;
> LIBHDFS_OPTS= -Xrs
> ```
> 
> 将上述环境变量增加到clion的环境变量中如下图： <img alt="image" width="1140" src="https://user-images.githubusercontent.com/41148123/203332383-776d609c-ca68-4a30-a22d-3637fa6d894d.png"> 然后就可以进行debug了 <img alt="image" width="1503" src="https://user-images.githubusercontent.com/41148123/203332487-ee7ed10b-c8b2-430a-8a25-ff27cf7836ab.png">

牛逼，你是能实现直接在 Clion 里面点击进行 debug 吗。测试用例那边能点点 debug 吗。

**Comment by tomscut** [comment]
👍

我单测和代码，都是直接远程debug了，比较慢。

huldarchen ***@***.***> 于2022年11月22日周二 21:59写道：

**Comment by huldarchen** [comment]
> 

c++不是很熟悉，这个单测不知道怎么进去。CMake中的这些应该都可以吧。
<img width="577" alt="image" src="https://user-images.githubusercontent.com/41148123/203462708-b3b1b394-05ac-4c82-a5d5-c0ce07758378.png">

**Comment by Smith-Cruise** [comment]
> > 
> 
> c++不是很熟悉，这个单测不知道怎么进去。CMake中的这些应该都可以吧。 <img alt="image" width="577" src="https://user-images.githubusercontent.com/41148123/203462708-b3b1b394-05ac-4c82-a5d5-c0ce07758378.png">

不知道，我都是命令行 gdb 调试的
